### ISSUE TITLE
`pyls`  doesn't get installed on Mac OS X via `pip`

### ISSUE THREAD

**Issue by appetrosyan** [tartley/pyls#1]
Hi. Can't get emacs-lsp-python to work, because pyls is not on the path. 

`pyls` in the command-line gives `command not found`. 

However, doing `python3 -m pyls` works just fine. Maybe the `pypi` package needs updating?

**Comment by antonzub1** [comment]
@appetrosyan looks like there is a slight confusion in module names for `python-language-server` and `pyls` packages. Both have `pyls` module inside, but for autocompletion one you should remove `pyls` and then install `python-language-server`. Hope it will help you.

**Comment by tartley** [comment]
Huge thank you for reporting back here when you figured it out.
